# -*- coding: utf-8 -*-
# ============================================================
# bestiario_prompts.py — las 126 especies de fauna tica del bestiario,
# cada una con su slug (key del juego), categoria, nombre, cientifico y
# prompt en ingles para PixelLab. Fuente unica para generar + manifest.
#
# Los slugs que YA tienen arte hecho a mano (jaguar, perezoso, tucan) se
# saltan en la generacion (no se sobrescriben).
# ============================================================

BESTIARIO = [
    # ---------------- Mamiferos ----------------
    {"slug": "perezoso",        "cat": "Mamíferos", "name": "Perezoso de tres dedos", "sci": "Bradypus variegatus",   "prompt": "a three-toed sloth hanging from a branch, brown fuzzy fur, dark eye mask, sleepy smile"},
    {"slug": "perezoso_dos",    "cat": "Mamíferos", "name": "Perezoso de dos dedos",  "sci": "Choloepus hoffmanni",   "prompt": "a two-toed sloth hanging, shaggy tan fur, long curved claws, round friendly face"},
    {"slug": "mono_congo",      "cat": "Mamíferos", "name": "Mono congo (aullador)",  "sci": "Alouatta palliata",     "prompt": "a mantled howler monkey, fluffy black fur with golden side fringe, sitting on a branch"},
    {"slug": "monocara",        "cat": "Mamíferos", "name": "Mono carablanca",        "sci": "Cebus imitator",        "prompt": "a white-faced capuchin monkey, black body, white face and shoulders"},
    {"slug": "mono_arana",      "cat": "Mamíferos", "name": "Mono araña",             "sci": "Ateles geoffroyi",      "prompt": "a black-handed spider monkey, long thin limbs and prehensile tail, hanging"},
    {"slug": "mono_titi",       "cat": "Mamíferos", "name": "Mono tití",              "sci": "Saimiri oerstedii",     "prompt": "a tiny squirrel monkey, orange back, white face mask, long tail"},
    {"slug": "jaguar",          "cat": "Mamíferos", "name": "Jaguar",                 "sci": "Panthera onca",         "prompt": "a spotted jaguar sitting, golden coat with black rosettes"},
    {"slug": "puma",            "cat": "Mamíferos", "name": "Puma",                   "sci": "Puma concolor",         "prompt": "a tan mountain lion puma sitting, plain sandy coat, long tail"},
    {"slug": "manigordo",       "cat": "Mamíferos", "name": "Manigordo (ocelote)",    "sci": "Leopardus pardalis",    "prompt": "an ocelot wildcat, golden fur with black rosette spots and stripes"},
    {"slug": "caucel",          "cat": "Mamíferos", "name": "Caucel (margay)",        "sci": "Leopardus wiedii",      "prompt": "a margay wildcat, very big round eyes, spotted coat, clinging to a branch"},
    {"slug": "leon_brenero",    "cat": "Mamíferos", "name": "León breñero (jaguarundi)", "sci": "Herpailurus yagouaroundi", "prompt": "a jaguarundi, slim dark grey weasel-like wildcat, long tail, low body"},
    {"slug": "tigrillo",        "cat": "Mamíferos", "name": "Tigrillo (oncilla)",     "sci": "Leopardus tigrinus",    "prompt": "an oncilla, small slender spotted wildcat, big eyes"},
    {"slug": "danta",           "cat": "Mamíferos", "name": "Danta (tapir)",          "sci": "Tapirus bairdii",       "prompt": "a Baird's tapir, bulky grey-brown body, short prehensile snout"},
    {"slug": "saino",           "cat": "Mamíferos", "name": "Saíno",                  "sci": "Dicotyles tajacu",      "prompt": "a collared peccary, dark bristly fur, pale collar, small tusks"},
    {"slug": "chancho_monte",   "cat": "Mamíferos", "name": "Chancho de monte",       "sci": "Tayassu pecari",        "prompt": "a white-lipped peccary, dark bristly fur, white muzzle"},
    {"slug": "venado",          "cat": "Mamíferos", "name": "Venado cola blanca",     "sci": "Odocoileus virginianus","prompt": "a white-tailed deer, tan coat, white throat, small antlers"},
    {"slug": "cabro_monte",     "cat": "Mamíferos", "name": "Cabro de monte",         "sci": "Mazama temama",         "prompt": "a red brocket deer, reddish-brown coat, short spike antlers"},
    {"slug": "pizote",          "cat": "Mamíferos", "name": "Pizote (coatí)",         "sci": "Nasua narica",          "prompt": "a coati, brown fur, long ringed tail held up, pointy upturned snout"},
    {"slug": "mapache",         "cat": "Mamíferos", "name": "Mapache",                "sci": "Procyon lotor",         "prompt": "a raccoon, grey fur, black eye mask, ringed bushy tail"},
    {"slug": "mapache_cangrejero","cat": "Mamíferos","name": "Mapache cangrejero",    "sci": "Procyon cancrivorus",   "prompt": "a crab-eating raccoon, sandy grey fur, black mask, slim body"},
    {"slug": "martilla",        "cat": "Mamíferos", "name": "Martilla (kinkajú)",     "sci": "Potos flavus",          "prompt": "a kinkajou, golden-brown fur, big eyes, curled prehensile tail"},
    {"slug": "olingo",          "cat": "Mamíferos", "name": "Olingo",                 "sci": "Bassaricyon gabbii",    "prompt": "an olingo, slender grey-brown fur, big eyes, long bushy tail"},
    {"slug": "tolomuco",        "cat": "Mamíferos", "name": "Tolomuco",               "sci": "Eira barbara",          "prompt": "a tayra, glossy black weasel body, brownish head"},
    {"slug": "grison",          "cat": "Mamíferos", "name": "Grisón",                 "sci": "Galictis vittata",      "prompt": "a grison, pale grey back, black face and underside, low long body"},
    {"slug": "nutria",          "cat": "Mamíferos", "name": "Nutria de río",          "sci": "Lontra longicaudis",    "prompt": "a neotropical river otter, sleek wet brown fur, swimming"},
    {"slug": "comadreja",       "cat": "Mamíferos", "name": "Comadreja",              "sci": "Mustela frenata",       "prompt": "a long-tailed weasel, slender brown body, cream belly"},
    {"slug": "zorro_pelon",     "cat": "Mamíferos", "name": "Zorro pelón (zarigüeya)","sci": "Didelphis marsupialis", "prompt": "a common opossum, grizzled grey fur, pink pointed face, bare tail"},
    {"slug": "oso_hormiguero",  "cat": "Mamíferos", "name": "Oso hormiguero (tamandúa)","sci": "Tamandua mexicana",   "prompt": "a northern tamandua anteater, tan body with black vest pattern, long snout"},
    {"slug": "serafin",         "cat": "Mamíferos", "name": "Serafín de platanar",    "sci": "Cyclopes didactylus",   "prompt": "a silky pygmy anteater, tiny golden fluffy ball curled on a branch"},
    {"slug": "armadillo",       "cat": "Mamíferos", "name": "Armadillo (cusuco)",     "sci": "Dasypus novemcinctus",  "prompt": "a nine-banded armadillo, banded armor shell, long snout, short legs"},
    {"slug": "tepezcuintle",    "cat": "Mamíferos", "name": "Tepezcuintle",           "sci": "Cuniculus paca",        "prompt": "a paca, brown fur with rows of white spots, stout body"},
    {"slug": "guatusa",         "cat": "Mamíferos", "name": "Guatusa",                "sci": "Dasyprocta punctata",   "prompt": "an agouti, sleek reddish-brown rodent, long thin legs"},
    {"slug": "ardilla",         "cat": "Mamíferos", "name": "Ardilla",                "sci": "Sciurus variegatoides", "prompt": "a variegated squirrel, reddish-brown fur, big bushy tail"},
    {"slug": "puercoespin",     "cat": "Mamíferos", "name": "Puercoespín",            "sci": "Coendou mexicanus",     "prompt": "a Mexican hairy dwarf porcupine, dark spiny coat, prehensile tail"},
    {"slug": "murcielago",      "cat": "Mamíferos", "name": "Murciélago pescador",    "sci": "Noctilio leporinus",    "prompt": "a fishing bulldog bat with spread wings, large hind feet"},
    {"slug": "coyote",          "cat": "Mamíferos", "name": "Coyote",                 "sci": "Canis latrans",         "prompt": "a coyote, grey-brown fur, pointed ears, bushy tail"},
    {"slug": "zorro_gris",      "cat": "Mamíferos", "name": "Zorro gris",             "sci": "Urocyon cinereoargenteus","prompt": "a grey fox, grizzled grey coat, rusty neck and legs"},
    {"slug": "manati",          "cat": "Mamíferos", "name": "Manatí del Caribe",      "sci": "Trichechus manatus",    "prompt": "a Caribbean manatee, large rounded grey body, paddle tail, gentle face"},
    {"slug": "delfin",          "cat": "Mamíferos", "name": "Delfín nariz de botella","sci": "Tursiops truncatus",    "prompt": "a bottlenose dolphin leaping, smooth grey body, friendly smile"},
    {"slug": "ballena",         "cat": "Mamíferos", "name": "Ballena jorobada",       "sci": "Megaptera novaeangliae","prompt": "a humpback whale, dark blue body, long white pectoral fins"},

    # ---------------- Aves ----------------
    {"slug": "yiguirro",        "cat": "Aves", "name": "Yigüirro (ave nacional)",     "sci": "Turdus grayi",          "prompt": "a clay-colored thrush, plain warm brown bird, pale orange beak"},
    {"slug": "quetzal",         "cat": "Aves", "name": "Quetzal resplandeciente",     "sci": "Pharomachrus mocinno",  "prompt": "a resplendent quetzal, emerald green body, crimson belly, long green tail streamers"},
    {"slug": "lapa",            "cat": "Aves", "name": "Lapa roja",                   "sci": "Ara macao",             "prompt": "a scarlet macaw, vivid red body, blue and yellow wings, long tail"},
    {"slug": "lapa_verde",      "cat": "Aves", "name": "Lapa verde",                  "sci": "Ara ambiguus",          "prompt": "a great green macaw, green body, red forehead, blue flight feathers"},
    {"slug": "tucan",           "cat": "Aves", "name": "Tucán pico iris",             "sci": "Ramphastos sulfuratus", "prompt": "a keel-billed toucan, black body, yellow chest, rainbow beak"},
    {"slug": "tucan_castano",   "cat": "Aves", "name": "Tucán pico castaño",          "sci": "Ramphastos ambiguus",   "prompt": "a yellow-throated toucan, black body, yellow bib, brown and yellow bill"},
    {"slug": "cusingo",         "cat": "Aves", "name": "Cusingo (arasarí)",           "sci": "Pteroglossus frantzii", "prompt": "a fiery-billed aracari, black head, yellow belly with red band, orange bill"},
    {"slug": "tucancillo",      "cat": "Aves", "name": "Tucancillo collarejo",        "sci": "Pteroglossus torquatus","prompt": "a collared aracari, black head, yellow underparts, red and black bill"},
    {"slug": "pajaro_campana",  "cat": "Aves", "name": "Pájaro campana",              "sci": "Procnias tricarunculatus","prompt": "a three-wattled bellbird, chestnut body, white head, dark wattles"},
    {"slug": "oropendola",      "cat": "Aves", "name": "Oropéndola de Moctezuma",     "sci": "Psarocolius montezuma", "prompt": "a Montezuma oropendola, chestnut body, black head, yellow tail, blue cheek patch"},
    {"slug": "colibri_fuego",   "cat": "Aves", "name": "Colibrí garganta de fuego",   "sci": "Panterpe insignis",     "prompt": "a fiery-throated hummingbird, glittering green body, orange-red throat, hovering"},
    {"slug": "colibri_talamanca","cat": "Aves","name": "Colibrí de Talamanca",        "sci": "Eugenes spectabilis",   "prompt": "a Talamanca hummingbird, green body, violet throat, hovering"},
    {"slug": "ermitano",        "cat": "Aves", "name": "Ermitaño verde",              "sci": "Phaethornis guy",       "prompt": "a green hermit hummingbird, green body, long curved bill, white tail tips"},
    {"slug": "jacamar",         "cat": "Aves", "name": "Jacamar coliroja",            "sci": "Galbula ruficauda",     "prompt": "a rufous-tailed jacamar, shiny green back, rufous belly, long needle bill"},
    {"slug": "momoto",          "cat": "Aves", "name": "Momoto cejiceleste",          "sci": "Eumomota superciliosa", "prompt": "a turquoise-browed motmot, turquoise brow, blue racket-tipped tail"},
    {"slug": "tangara_azul",    "cat": "Aves", "name": "Tangara azuleja (viudita)",   "sci": "Thraupis episcopus",    "prompt": "a blue-gray tanager, soft powder blue songbird"},
    {"slug": "tangara_dorada",  "cat": "Aves", "name": "Tangara dorada",              "sci": "Tangara icterocephala", "prompt": "a golden-hooded tanager, golden head, black back, blue and white body"},
    {"slug": "bienteveo",       "cat": "Aves", "name": "Bienteveo (mosquero)",        "sci": "Pitangus sulphuratus",  "prompt": "a great kiskadee, bright yellow belly, black and white striped head, brown wings"},
    {"slug": "garza",           "cat": "Aves", "name": "Garza real",                  "sci": "Ardea alba",            "prompt": "a great egret, all white heron, long S-curved neck, yellow dagger bill"},
    {"slug": "espatula",        "cat": "Aves", "name": "Espátula rosada",             "sci": "Platalea ajaja",        "prompt": "a roseate spoonbill, pink plumage, spoon-shaped bill, long legs"},
    {"slug": "jabiru",          "cat": "Aves", "name": "Jabirú",                      "sci": "Jabiru mycteria",       "prompt": "a jabiru stork, white body, black bald head, red neck band, long bill"},
    {"slug": "tantalo",         "cat": "Aves", "name": "Tántalo americano (garzón)",  "sci": "Mycteria americana",    "prompt": "a wood stork, white body, dark scaly bald head, long down-curved bill"},
    {"slug": "ibis",            "cat": "Aves", "name": "Ibis blanco",                 "sci": "Eudocimus albus",       "prompt": "a white ibis, white body, long curved orange bill, pink legs"},
    {"slug": "pelicano",        "cat": "Aves", "name": "Pelícano pardo",              "sci": "Pelecanus occidentalis","prompt": "a brown pelican, grey-brown body, long pouched bill"},
    {"slug": "fragata",         "cat": "Aves", "name": "Rabihorcado (fragata)",       "sci": "Fregata magnificens",   "prompt": "a magnificent frigatebird, black body, red inflated throat pouch, forked tail"},
    {"slug": "aguila_harpia",   "cat": "Aves", "name": "Águila harpía",               "sci": "Harpia harpyja",        "prompt": "a harpy eagle, grey and white plumage, double feather crest, fierce stare"},
    {"slug": "caracara",        "cat": "Aves", "name": "Caracara",                    "sci": "Caracara plancus",      "prompt": "a crested caracara, black body, white neck, black cap, orange face"},
    {"slug": "zopilote_negro",  "cat": "Aves", "name": "Zopilote negro",              "sci": "Coragyps atratus",      "prompt": "a black vulture, black plumage, bald grey wrinkled head"},
    {"slug": "zopilote_rojo",   "cat": "Aves", "name": "Zopilote cabecirrojo",        "sci": "Cathartes aura",        "prompt": "a turkey vulture, dark brown plumage, bald red head"},
    {"slug": "lechuza",         "cat": "Aves", "name": "Lechuza de campanario",       "sci": "Tyto alba",             "prompt": "a barn owl, white heart-shaped face, golden-buff back, dark eyes"},
    {"slug": "carpintero",      "cat": "Aves", "name": "Pájaro carpintero",           "sci": "Melanerpes hoffmannii", "prompt": "a Hoffmann's woodpecker, black-and-white barred back, red crown, yellow nape"},
    {"slug": "saltarin",        "cat": "Aves", "name": "Saltarín toledo",             "sci": "Chiroxiphia linearis",  "prompt": "a long-tailed manakin, black body, sky-blue back, red cap, long tail wires"},
    {"slug": "trogon",          "cat": "Aves", "name": "Trogón",                      "sci": "Trogon collaris",       "prompt": "a collared trogon, green back, red belly, white chest band, barred tail"},
    {"slug": "martin_pescador", "cat": "Aves", "name": "Martín pescador",             "sci": "Megaceryle torquata",   "prompt": "a ringed kingfisher, blue-grey back, rufous belly, shaggy crest, heavy bill"},
    {"slug": "anhinga",         "cat": "Aves", "name": "Pato aguja (anhinga)",        "sci": "Anhinga anhinga",       "prompt": "an anhinga, black body, silvery wing streaks, long snake-like neck, sharp bill"},
    {"slug": "tinamu",          "cat": "Aves", "name": "Tinamú grande",               "sci": "Tinamus major",         "prompt": "a great tinamou, plump brown ground bird, small head, short tail"},
    {"slug": "chachalaca",      "cat": "Aves", "name": "Chachalaca",                  "sci": "Ortalis cinereiceps",   "prompt": "a grey-headed chachalaca, brown body, grey head, long tail"},
    {"slug": "loro",            "cat": "Aves", "name": "Loro frentirrojo",            "sci": "Amazona autumnalis",    "prompt": "a red-lored parrot, green body, red forehead, lilac crown touch"},

    # ---------------- Anfibios ----------------
    {"slug": "rana_ojos_rojos", "cat": "Anfibios", "name": "Rana de ojos rojos",      "sci": "Agalychnis callidryas", "prompt": "a red-eyed tree frog, leaf-green body, big red eyes, blue flanks, orange feet"},
    {"slug": "ranadardo",       "cat": "Anfibios", "name": "Rana venenosa roja (blue-jeans)", "sci": "Oophaga pumilio", "prompt": "a strawberry poison dart frog, bright red body, blue jeans legs"},
    {"slug": "rana_verdinegra", "cat": "Anfibios", "name": "Rana dardo verdinegra",   "sci": "Dendrobates auratus",   "prompt": "a green and black poison dart frog, marbled pattern"},
    {"slug": "rana_cristal",    "cat": "Anfibios", "name": "Rana de cristal",         "sci": "Hyalinobatrachium valerioi","prompt": "a glass frog, translucent lime-green body, visible heart, on a leaf"},
    {"slug": "rana_lechera",    "cat": "Anfibios", "name": "Rana lechera",            "sci": "Leptodactylus savagei", "prompt": "a smoky jungle frog, large robust brown frog, folds on sides"},
    {"slug": "rana_tungara",    "cat": "Anfibios", "name": "Rana túngara",            "sci": "Engystomops pustulosus", "prompt": "a tungara frog, small warty greyish-brown frog"},
    {"slug": "rana_gladiadora", "cat": "Anfibios", "name": "Rana arbórea gladiadora", "sci": "Boana rufitela",        "prompt": "a gladiator tree frog, tan body, large eyes, long legs"},
    {"slug": "rana_payaso",     "cat": "Anfibios", "name": "Rana payaso",             "sci": "Dendropsophus ebraccatus","prompt": "an hourglass tree frog, yellow-tan body with brown hourglass mark"},
    {"slug": "sapo_marino",     "cat": "Anfibios", "name": "Sapo marino",             "sci": "Rhinella marina",       "prompt": "a cane toad, large warty olive-brown toad, big parotoid glands"},
    {"slug": "sapo_dorado",     "cat": "Anfibios", "name": "Sapo dorado (extinto)",   "sci": "Incilius periglenes",   "prompt": "a golden toad, bright glowing orange smooth toad", "ext": True},
    {"slug": "salamandra",      "cat": "Anfibios", "name": "Salamandra sin pulmones", "sci": "Bolitoglossa",          "prompt": "a lungless salamander, slender moist dark-brown body, tiny legs"},

    # ---------------- Reptiles ----------------
    {"slug": "iguana",          "cat": "Reptiles", "name": "Iguana verde",            "sci": "Iguana iguana",         "prompt": "a green iguana on a branch, spiky dorsal crest, dewlap, long striped tail"},
    {"slug": "garrobo",         "cat": "Reptiles", "name": "Garrobo",                 "sci": "Ctenosaura similis",    "prompt": "a black spiny-tailed iguana, grey body with dark bands, spiky tail"},
    {"slug": "basilisco",       "cat": "Reptiles", "name": "Basilisco verde (Jesucristo)","sci": "Basiliscus plumifrons","prompt": "a green plumed basilisk, vivid green, tall head and back crest, on hind legs"},
    {"slug": "anolis",          "cat": "Reptiles", "name": "Anolis (lagartija)",      "sci": "Anolis",                "prompt": "a small anole lizard, slender green-brown body, extended orange throat fan"},
    {"slug": "geco",            "cat": "Reptiles", "name": "Salamanqueja (geco)",     "sci": "Hemidactylus",          "prompt": "a house gecko, pale tan translucent skin, big eyes, sticky toes"},
    {"slug": "cocodrilo",       "cat": "Reptiles", "name": "Cocodrilo americano",     "sci": "Crocodylus acutus",     "prompt": "an American crocodile, olive-green armored body, long toothy snout"},
    {"slug": "caiman",          "cat": "Reptiles", "name": "Caimán (guajipal)",       "sci": "Caiman crocodilus",     "prompt": "a spectacled caiman, dark olive scaly body, bony ridge between the eyes"},
    {"slug": "boa",             "cat": "Reptiles", "name": "Boa (béquer)",            "sci": "Boa imperator",         "prompt": "a boa constrictor coiled, tan body with dark saddle blotches"},
    {"slug": "serpiente",       "cat": "Reptiles", "name": "Terciopelo",              "sci": "Bothrops asper",        "prompt": "a fer-de-lance pit viper coiled, brown and tan diamond pattern, triangular head"},
    {"slug": "bocaraca",        "cat": "Reptiles", "name": "Bocaracá",                "sci": "Bothriechis schlegelii","prompt": "an eyelash pit viper coiled on a branch, golden-yellow, eyelash scales over the eyes"},
    {"slug": "lora",            "cat": "Reptiles", "name": "Lora (víbora verde)",     "sci": "Bothriechis lateralis", "prompt": "a side-striped palm pitviper, bright green snake coiled on a branch"},
    {"slug": "cascabel",        "cat": "Reptiles", "name": "Cascabel",                "sci": "Crotalus simus",        "prompt": "a tropical rattlesnake coiled, tan with dark diamonds, rattle tail raised"},
    {"slug": "matabuey",        "cat": "Reptiles", "name": "Matabuey (bushmaster)",   "sci": "Lachesis stenophrys",   "prompt": "a bushmaster, large tan viper with dark diamond pattern, coiled"},
    {"slug": "coral",           "cat": "Reptiles", "name": "Coral",                   "sci": "Micrurus nigrocinctus", "prompt": "a coral snake, glossy red, black and yellow ringed body"},
    {"slug": "serpiente_mar",   "cat": "Reptiles", "name": "Serpiente de mar",        "sci": "Hydrophis platurus",    "prompt": "a yellow-bellied sea snake, black back, bright yellow belly, paddle tail, swimming"},
    {"slug": "mica",            "cat": "Reptiles", "name": "Mica (zopilota)",         "sci": "Spilotes pullatus",     "prompt": "a tropical rat snake, black body with yellow bands, slender, climbing"},
    {"slug": "bejuquilla",      "cat": "Reptiles", "name": "Bejuquilla",              "sci": "Oxybelis aeneus",       "prompt": "a brown vine snake, extremely thin twig-like body, pointed snout, on a branch"},
    {"slug": "tortuga_baula",   "cat": "Reptiles", "name": "Tortuga baula",           "sci": "Dermochelys coriacea",  "prompt": "a leatherback sea turtle, dark ridged leathery shell, large flippers, swimming"},
    {"slug": "tortuga",         "cat": "Reptiles", "name": "Tortuga verde",           "sci": "Chelonia mydas",        "prompt": "a green sea turtle swimming, smooth patterned shell, flippers"},
    {"slug": "tortuga_carey",   "cat": "Reptiles", "name": "Tortuga carey",           "sci": "Eretmochelys imbricata","prompt": "a hawksbill sea turtle, amber and brown patterned shell, pointed beak"},
    {"slug": "tortuga_lora",    "cat": "Reptiles", "name": "Tortuga lora (golfina)",  "sci": "Lepidochelys olivacea", "prompt": "an olive ridley sea turtle, olive heart-shaped shell, swimming"},
    {"slug": "tortuga_cabezona","cat": "Reptiles", "name": "Tortuga cabezona",        "sci": "Caretta caretta",       "prompt": "a loggerhead sea turtle, large blocky head, reddish-brown shell"},
    {"slug": "jicotea",         "cat": "Reptiles", "name": "Jicotea",                 "sci": "Trachemys venusta",     "prompt": "a freshwater slider turtle, olive shell, yellow-striped skin, on a log"},

    # ---------------- Marinos e insectos ----------------
    {"slug": "tiburon_martillo","cat": "Marinos e insectos", "name": "Tiburón martillo","sci": "Sphyrna lewini",      "prompt": "a scalloped hammerhead shark, grey body, wide flat hammer head"},
    {"slug": "tiburon_ballena", "cat": "Marinos e insectos", "name": "Tiburón ballena", "sci": "Rhincodon typus",     "prompt": "a whale shark, huge blue-grey body covered in white spots, wide mouth"},
    {"slug": "pez_vela",        "cat": "Marinos e insectos", "name": "Pez vela",        "sci": "Istiophorus platypterus","prompt": "a sailfish, sleek silvery-blue fish, tall raised dorsal sail, long bill"},
    {"slug": "marlin",          "cat": "Marinos e insectos", "name": "Marlin azul",     "sci": "Makaira nigricans",   "prompt": "a blue marlin, cobalt back, silver belly, long spear bill, powerful body"},
    {"slug": "mantarraya",      "cat": "Marinos e insectos", "name": "Mantarraya",      "sci": "Mobula birostris",    "prompt": "a giant manta ray, black back, white belly, broad triangular wings, gliding"},
    {"slug": "mariposa",        "cat": "Marinos e insectos", "name": "Mariposa morfo azul","sci": "Morpho helenor",   "prompt": "a blue morpho butterfly, iridescent metallic blue wings spread open"},
    {"slug": "mariposa_buho",   "cat": "Marinos e insectos", "name": "Mariposa búho",   "sci": "Caligo memnon",       "prompt": "an owl butterfly, large brown wings each with a big owl-eye spot"},
    {"slug": "mariposa_julia",  "cat": "Marinos e insectos", "name": "Mariposa Julia",  "sci": "Dryas iulia",         "prompt": "a Julia butterfly, bright orange elongated wings spread"},
    {"slug": "hormiga_bala",    "cat": "Marinos e insectos", "name": "Hormiga bala",    "sci": "Paraponera clavata",  "prompt": "a bullet ant, large glossy reddish-black ant, big mandibles"},
    {"slug": "escarabajo",      "cat": "Marinos e insectos", "name": "Escarabajo Hércules","sci": "Dynastes hercules","prompt": "a Hercules beetle, black body, olive wing cases, long curved horn"},
]
