// ============================================================
// fauna_roster.js — GENERADO por make_fauna_data.py. NO editar a mano.
// Roster completo de fauna tica (126 especies) + pools por provincia.
// Stats/bioma/efecto auto-asignados por arquetipo; los 27 base y los
// legendarios van con sus valores curados. Re-generar: python make_fauna_data.py
// ============================================================

// 130 especies (128 jugables en pools + legendarios)
export const SP = {
  perezoso: { n:"Perezoso", e:"🦥", atk:1, hp:7, spd:1, bio:"bosque", ab:"heal" },
  perezoso_dos: { n:"Perezoso de dos dedos", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"heal" },
  mono_congo: { n:"Mono congo (aullador)", e:"🐾", atk:6, hp:5, spd:5, bio:"bosque", ab:"rage" },
  monocara: { n:"Mono carablanca", e:"🐒", atk:2, hp:3, spd:8, bio:"bosque", ab:"first" },
  mono_arana: { n:"Mono araña", e:"🐾", atk:2, hp:2, spd:8, bio:"bosque", ab:"first" },
  mono_titi: { n:"Mono tití", e:"🐾", atk:1, hp:4, spd:8, bio:"bosque", ab:"first" },
  jaguar: { n:"Jaguar", e:"🐆", atk:5, hp:4, spd:7, bio:"bosque", ab:"rage" },
  puma: { n:"Puma", e:"🐆", atk:5, hp:5, spd:7, bio:"montana", ab:"rage" },
  manigordo: { n:"Manigordo", e:"🐈", atk:3, hp:3, spd:8, bio:"bosque", ab:"first" },
  caucel: { n:"Caucel (margay)", e:"🐾", atk:4, hp:6, spd:6, bio:"bosque", ab:"first" },
  leon_brenero: { n:"León breñero (jaguarundi)", e:"🐾", atk:6, hp:5, spd:5, bio:"bosque", ab:"rage" },
  tigrillo: { n:"Tigrillo (oncilla)", e:"🐾", atk:4, hp:6, spd:6, bio:"bosque", ab:"first" },
  danta: { n:"Danta (tapir)", e:"🐾", atk:2, hp:7, spd:3, bio:"bosque", ab:"shield" },
  saino: { n:"Saíno", e:"🐗", atk:4, hp:5, spd:4, bio:"sabana", ab:"rage" },
  chancho_monte: { n:"Chancho de monte", e:"🐾", atk:5, hp:4, spd:7, bio:"bosque", ab:"rage" },
  venado: { n:"Venado", e:"🦌", atk:2, hp:6, spd:7, bio:"sabana", ab:"shield" },
  cabro_monte: { n:"Cabro de monte", e:"🐾", atk:2, hp:5, spd:5, bio:"montana", ab:"first" },
  pizote: { n:"Pizote", e:"🦝", atk:3, hp:4, spd:5, bio:"bosque", ab:"first" },
  mapache: { n:"Mapache", e:"🐾", atk:4, hp:4, spd:4, bio:"bosque", ab:"first" },
  mapache_cangrejero: { n:"Mapache cangrejero", e:"🐾", atk:3, hp:3, spd:6, bio:"agua", ab:"first" },
  martilla: { n:"Martilla (kinkajú)", e:"🐾", atk:4, hp:4, spd:4, bio:"bosque", ab:"heal" },
  olingo: { n:"Olingo", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"first" },
  tolomuco: { n:"Tolomuco", e:"🐾", atk:4, hp:6, spd:6, bio:"bosque", ab:"rage" },
  grison: { n:"Grisón", e:"🐾", atk:5, hp:4, spd:7, bio:"sabana", ab:"first" },
  nutria: { n:"Nutria de río", e:"🐾", atk:4, hp:4, spd:4, bio:"agua", ab:"first" },
  comadreja: { n:"Comadreja", e:"🐾", atk:2, hp:2, spd:8, bio:"montana", ab:"first" },
  zorro_pelon: { n:"Zorro pelón (zarigüeya)", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"first" },
  oso_hormiguero: { n:"Oso hormiguero (tamandúa)", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"first" },
  serafin: { n:"Serafín de platanar", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"heal" },
  armadillo: { n:"Armadillo (cusuco)", e:"🐾", atk:2, hp:7, spd:3, bio:"sabana", ab:"shield" },
  tepezcuintle: { n:"Tepezcuintle", e:"🐾", atk:1, hp:9, spd:2, bio:"bosque", ab:"shield" },
  guatusa: { n:"Guatusa", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"first" },
  ardilla: { n:"Ardilla", e:"🐾", atk:1, hp:4, spd:8, bio:"bosque", ab:"first" },
  puercoespin: { n:"Puercoespín", e:"🐾", atk:2, hp:5, spd:5, bio:"bosque", ab:"thorns" },
  murcielago: { n:"Murciélago", e:"🦇", atk:3, hp:2, spd:8, bio:"bosque", ab:"poison" },
  coyote: { n:"Coyote", e:"🐺", atk:4, hp:3, spd:7, bio:"montana", ab:"first" },
  zorro_gris: { n:"Zorro gris", e:"🐾", atk:2, hp:5, spd:5, bio:"sabana", ab:"first" },
  manati: { n:"Manatí del Caribe", e:"🐾", atk:2, hp:7, spd:3, bio:"agua", ab:"shield" },
  delfin: { n:"Delfín", e:"🐬", atk:3, hp:3, spd:8, bio:"agua", ab:"first" },
  ballena: { n:"Ballena jorobada", e:"🐋", atk:6, hp:8, spd:3, bio:"agua", ab:"rage" },
  yiguirro: { n:"Yigüirro (ave nacional)", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"heal" },
  quetzal: { n:"Quetzal", e:"🐦", atk:2, hp:4, spd:7, bio:"montana", ab:"heal" },
  lapa: { n:"Lapa roja", e:"🦜", atk:5, hp:6, spd:6, bio:"bosque", ab:"rage", leg:true },
  lapa_verde: { n:"Lapa verde", e:"🐦", atk:4, hp:4, spd:4, bio:"bosque", ab:"first" },
  tucan: { n:"Tucán", e:"🦜", atk:2, hp:3, spd:8, bio:"bosque", ab:"first" },
  tucan_castano: { n:"Tucán pico castaño", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  cusingo: { n:"Cusingo (arasarí)", e:"🐦", atk:2, hp:2, spd:8, bio:"bosque", ab:"first" },
  tucancillo: { n:"Tucancillo collarejo", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  pajaro_campana: { n:"Pájaro campana", e:"🐦", atk:3, hp:3, spd:6, bio:"montana", ab:"first" },
  oropendola: { n:"Oropéndola de Moctezuma", e:"🐦", atk:3, hp:3, spd:6, bio:"bosque", ab:"first" },
  colibri_fuego: { n:"Colibrí garganta de fuego", e:"🐦", atk:2, hp:2, spd:8, bio:"montana", ab:"first" },
  colibri_talamanca: { n:"Colibrí de Talamanca", e:"🐦", atk:2, hp:2, spd:8, bio:"montana", ab:"first" },
  ermitano: { n:"Ermitaño verde", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  jacamar: { n:"Jacamar coliroja", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  momoto: { n:"Momoto cejiceleste", e:"🐦", atk:2, hp:2, spd:8, bio:"sabana", ab:"first" },
  tangara_azul: { n:"Tangara azuleja (viudita)", e:"🐦", atk:2, hp:2, spd:8, bio:"bosque", ab:"first" },
  tangara_dorada: { n:"Tangara dorada", e:"🐦", atk:3, hp:3, spd:7, bio:"montana", ab:"first" },
  bienteveo: { n:"Bienteveo (mosquero)", e:"🐦", atk:2, hp:2, spd:8, bio:"sabana", ab:"first" },
  garza: { n:"Garza", e:"🐦", atk:2, hp:3, spd:6, bio:"sabana", ab:"first" },
  espatula: { n:"Espátula rosada", e:"🐦", atk:4, hp:4, spd:4, bio:"agua", ab:"first" },
  jabiru: { n:"Jabirú", e:"🐦", atk:3, hp:3, spd:6, bio:"agua", ab:"first" },
  tantalo: { n:"Tántalo americano (garzón)", e:"🐦", atk:4, hp:4, spd:4, bio:"agua", ab:"first" },
  ibis: { n:"Ibis blanco", e:"🐦", atk:2, hp:5, spd:5, bio:"agua", ab:"first" },
  pelicano: { n:"Pelícano pardo", e:"🐦", atk:2, hp:5, spd:5, bio:"agua", ab:"first" },
  fragata: { n:"Rabihorcado (fragata)", e:"🐦", atk:2, hp:5, spd:5, bio:"agua", ab:"first" },
  aguila_harpia: { n:"Águila harpía", e:"🐦", atk:5, hp:4, spd:7, bio:"bosque", ab:"rage" },
  caracara: { n:"Caracara", e:"🐦", atk:5, hp:4, spd:7, bio:"sabana", ab:"rage" },
  zopilote_negro: { n:"Zopilote negro", e:"🐦", atk:4, hp:4, spd:4, bio:"sabana", ab:"first" },
  zopilote_rojo: { n:"Zopilote cabecirrojo", e:"🐦", atk:3, hp:3, spd:6, bio:"sabana", ab:"first" },
  lechuza: { n:"Lechuza de campanario", e:"🐦", atk:3, hp:3, spd:6, bio:"bosque", ab:"first" },
  carpintero: { n:"Pájaro carpintero", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  saltarin: { n:"Saltarín toledo", e:"🐦", atk:2, hp:2, spd:8, bio:"bosque", ab:"first" },
  trogon: { n:"Trogón", e:"🐦", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  martin_pescador: { n:"Martín pescador", e:"🐦", atk:4, hp:4, spd:4, bio:"agua", ab:"first" },
  anhinga: { n:"Pato aguja (anhinga)", e:"🐦", atk:2, hp:5, spd:5, bio:"agua", ab:"first" },
  tinamu: { n:"Tinamú grande", e:"🐦", atk:2, hp:5, spd:5, bio:"bosque", ab:"first" },
  pavon: { n:"Pavón grande", e:"🐦", atk:6, hp:5, spd:5, bio:"bosque", ab:"rage" },
  chachalaca: { n:"Chachalaca", e:"🐦", atk:4, hp:4, spd:4, bio:"bosque", ab:"first" },
  loro: { n:"Loro frentirrojo", e:"🐦", atk:1, hp:4, spd:8, bio:"bosque", ab:"heal" },
  rana_ojos_rojos: { n:"Rana de ojos rojos", e:"🐸", atk:4, hp:2, spd:5, bio:"bosque", ab:"poison" },
  ranadardo: { n:"Rana dardo", e:"🐸", atk:4, hp:1, spd:4, bio:"bosque", ab:"poison" },
  rana_verdinegra: { n:"Rana dardo verdinegra", e:"🐸", atk:5, hp:1, spd:6, bio:"bosque", ab:"poison" },
  rana_granular: { n:"Rana dardo granular", e:"🐸", atk:6, hp:1, spd:4, bio:"bosque", ab:"poison" },
  rana_cristal: { n:"Rana de cristal", e:"🐸", atk:3, hp:3, spd:6, bio:"bosque", ab:"first" },
  rana_lechera: { n:"Rana lechera", e:"🐸", atk:3, hp:3, spd:6, bio:"bosque", ab:"first" },
  rana_tungara: { n:"Rana túngara", e:"🐸", atk:3, hp:3, spd:6, bio:"sabana", ab:"first" },
  rana_gladiadora: { n:"Rana arbórea gladiadora", e:"🐸", atk:2, hp:5, spd:5, bio:"bosque", ab:"first" },
  rana_payaso: { n:"Rana payaso", e:"🐸", atk:6, hp:1, spd:4, bio:"bosque", ab:"poison" },
  sapo_marino: { n:"Sapo marino", e:"🐸", atk:2, hp:5, spd:5, bio:"sabana", ab:"poison" },
  sapo_dorado: { n:"Sapo dorado (extinto)", e:"🐸", atk:6, hp:1, spd:4, bio:"montana", ab:"poison", ext:true },
  salamandra: { n:"Salamandra sin pulmones", e:"🐸", atk:2, hp:5, spd:5, bio:"montana", ab:"heal" },
  cecilia: { n:"Cecilia", e:"🐸", atk:4, hp:2, spd:5, bio:"bosque", ab:"poison" },
  iguana: { n:"Iguana", e:"🦎", atk:2, hp:5, spd:4, bio:"sabana", ab:"thorns" },
  garrobo: { n:"Garrobo", e:"🦎", atk:3, hp:3, spd:6, bio:"sabana", ab:"thorns" },
  basilisco: { n:"Basilisco", e:"🦎", atk:3, hp:3, spd:8, bio:"agua", ab:"first" },
  basilisco_comun: { n:"Basilisco común", e:"🦎", atk:3, hp:3, spd:6, bio:"agua", ab:"thorns" },
  anolis: { n:"Anolis (lagartija)", e:"🦎", atk:2, hp:2, spd:8, bio:"bosque", ab:"thorns" },
  geco: { n:"Salamanqueja (geco)", e:"🦎", atk:1, hp:4, spd:8, bio:"bosque", ab:"first" },
  cocodrilo: { n:"Cocodrilo", e:"🐊", atk:5, hp:6, spd:3, bio:"agua", ab:"first" },
  caiman: { n:"Caimán (guajipal)", e:"🦎", atk:3, hp:8, spd:1, bio:"agua", ab:"rage" },
  boa: { n:"Boa (béquer)", e:"🦎", atk:4, hp:6, spd:6, bio:"bosque", ab:"poison" },
  serpiente: { n:"Terciopelo", e:"🐍", atk:5, hp:2, spd:6, bio:"bosque", ab:"poison" },
  bocaraca: { n:"Bocaracá", e:"🦎", atk:6, hp:1, spd:4, bio:"bosque", ab:"poison" },
  lora: { n:"Lora (víbora verde)", e:"🦎", atk:3, hp:3, spd:6, bio:"montana", ab:"poison" },
  cascabel: { n:"Cascabel", e:"🦎", atk:5, hp:4, spd:7, bio:"sabana", ab:"poison" },
  matabuey: { n:"Matabuey (bushmaster)", e:"🦎", atk:5, hp:4, spd:7, bio:"bosque", ab:"poison" },
  coral: { n:"Coral", e:"🦎", atk:5, hp:1, spd:6, bio:"bosque", ab:"poison" },
  serpiente_mar: { n:"Serpiente de mar", e:"🦎", atk:5, hp:1, spd:6, bio:"agua", ab:"poison" },
  mica: { n:"Mica (zopilota)", e:"🦎", atk:6, hp:5, spd:5, bio:"bosque", ab:"poison" },
  bejuquilla: { n:"Bejuquilla", e:"🦎", atk:4, hp:4, spd:4, bio:"bosque", ab:"poison" },
  tortuga_baula: { n:"Tortuga baula", e:"🦎", atk:1, hp:9, spd:2, bio:"agua", ab:"shield" },
  tortuga: { n:"Tortuga verde", e:"🐢", atk:1, hp:8, spd:1, bio:"agua", ab:"shield" },
  tortuga_carey: { n:"Tortuga carey", e:"🦎", atk:1, hp:9, spd:2, bio:"agua", ab:"shield" },
  tortuga_lora: { n:"Tortuga lora (golfina)", e:"🦎", atk:1, hp:9, spd:2, bio:"agua", ab:"shield" },
  tortuga_cabezona: { n:"Tortuga cabezona", e:"🦎", atk:1, hp:9, spd:2, bio:"agua", ab:"shield" },
  jicotea: { n:"Jicotea", e:"🦎", atk:1, hp:9, spd:2, bio:"agua", ab:"shield" },
  tiburon_martillo: { n:"Tiburón martillo", e:"🐟", atk:4, hp:6, spd:6, bio:"agua", ab:"rage" },
  tiburon_ballena: { n:"Tiburón ballena", e:"🐟", atk:2, hp:7, spd:3, bio:"agua", ab:"shield" },
  pez_vela: { n:"Pez vela", e:"🐟", atk:6, hp:5, spd:5, bio:"agua", ab:"rage" },
  marlin: { n:"Marlin azul", e:"🐟", atk:5, hp:4, spd:7, bio:"agua", ab:"rage" },
  mantarraya: { n:"Mantarraya", e:"🐟", atk:3, hp:3, spd:6, bio:"agua", ab:"first" },
  mariposa: { n:"Morfo azul", e:"🦋", atk:2, hp:2, spd:7, bio:"bosque", ab:"first" },
  mariposa_buho: { n:"Mariposa búho", e:"🐟", atk:3, hp:3, spd:7, bio:"bosque", ab:"first" },
  mariposa_julia: { n:"Mariposa Julia", e:"🐟", atk:1, hp:4, spd:8, bio:"bosque", ab:"first" },
  hormiga_bala: { n:"Hormiga bala", e:"🐟", atk:6, hp:1, spd:4, bio:"bosque", ab:"poison" },
  escarabajo: { n:"Escarabajo Hércules", e:"🐟", atk:2, hp:5, spd:5, bio:"bosque", ab:"thorns" },
  abeja: { n:"Abeja", e:"🐝", atk:3, hp:1, spd:7, bio:"bosque", ab:"poison" },
  cangrejo: { n:"Cangrejo", e:"🦀", atk:2, hp:5, spd:3, bio:"agua", ab:"thorns" },
  tiburon: { n:"Tiburón", e:"🦈", atk:6, hp:4, spd:6, bio:"agua", ab:"rage" },
  quetzaldorado: { n:"Quetzal Dorado", e:"🐦", atk:4, hp:9, spd:8, bio:"montana", ab:"heal", leg:true },
};

export const COUNTRIES = [
  { flag:"🏙️", n:"San José", map:"costa-rica", pool:["abeja", "bejuquilla", "cabro_monte", "colibri_fuego", "coyote", "geco", "jacamar", "lora", "mariposa", "matabuey", "monocara", "pajaro_campana", "puma", "rana_payaso", "sapo_dorado", "tepezcuintle", "tolomuco", "tucan_castano", "perezoso"] },
  { flag:"🌋", n:"Alajuela", map:"costa-rica", pool:["aguila_harpia", "basilisco_comun", "carpintero", "cocodrilo", "danta", "fragata", "jaguar", "loro", "mapache_cangrejero", "martin_pescador", "murcielago", "pelicano", "quetzal", "rana_verdinegra", "serpiente", "tiburon", "tortuga", "tortuga_lora", "tucan"] },
  { flag:"⛰️", n:"Cartago", map:"costa-rica", pool:["anolis", "boa", "caucel", "colibri_talamanca", "ermitano", "guatusa", "lapa_verde", "manigordo", "mariposa_buho", "mica", "olingo", "perezoso", "rana_cristal", "ranadardo", "tangara_azul", "tigrillo", "trogon", "tucancillo", "quetzal"] },
  { flag:"🌿", n:"Heredia", map:"costa-rica", pool:["ardilla", "bocaraca", "cecilia", "comadreja", "escarabajo", "hormiga_bala", "lechuza", "mapache", "mariposa_julia", "mono_arana", "oropendola", "perezoso_dos", "rana_gladiadora", "salamandra", "tangara_dorada", "tinamu", "tucan", "yiguirro"] },
  { flag:"🌾", n:"Guanacaste", map:"costa-rica", legend:"lapa", pool:["anhinga", "armadillo", "bienteveo", "caracara", "cascabel", "garrobo", "garza", "grison", "iguana", "momoto", "nutria", "pez_vela", "rana_granular", "rana_tungara", "saino", "sapo_marino", "tortuga_baula", "venado", "zopilote_negro", "zopilote_rojo", "zorro_gris"] },
  { flag:"🌊", n:"Puntarenas", map:"costa-rica", legend:"lapa", pool:["ballena", "caiman", "chachalaca", "coral", "delfin", "ibis", "jicotea", "manati", "marlin", "mono_congo", "oso_hormiguero", "pizote", "rana_lechera", "saltarin", "serpiente_mar", "tiburon_ballena", "tortuga_cabezona", "zorro_pelon", "tortuga"] },
  { flag:"🏝️", n:"Limón", map:"costa-rica", pool:["basilisco", "cangrejo", "chancho_monte", "cusingo", "espatula", "jabiru", "leon_brenero", "mantarraya", "martilla", "mono_titi", "pavon", "puercoespin", "rana_ojos_rojos", "serafin", "tantalo", "tiburon_martillo", "tortuga_carey", "jaguar", "cocodrilo"] },
];

export const SECRET = {
  flag:"☁️", n:"Monteverde", map:"costa-rica", secret:true, legend:"quetzaldorado",
  pool:["cabro_monte", "colibri_fuego", "colibri_talamanca", "comadreja", "coyote", "lora", "pajaro_campana", "puma", "quetzal", "salamandra", "sapo_dorado", "tangara_dorada", "abeja", "aguila_harpia"],
};
