// ============================================================
// movesets_doc.js — GENERADO por make_habilidades_doc.py. NO editar a mano.
// Kits OFICIALES: salen del documento de Andrés (722 habilidades, 100
// animales, portadas de Naruto-Arena). Cada animal trae sus 4 habilidades
// + la esquiva universal que agrega arena.js.
// Chakra -> bioma:  Taijutsu=🌳bosque · Ninjutsu=🌊agua ·
//                   Bloodline=⛰montaña · Genjutsu=🌾sabana · Random=⚪comodín
// ============================================================

export const MOVESETS_DOC = {
  // Oboro · Original (Parte 1)
  rana_cristal: { habs: [
    { n:"Lengua pegajosa", desc:"15 de daño a TODOS los enemigos.",
      costo:["comodin", "comodin"], recarga:0, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "todos"}] },
    { n:"Toxina paralizante", desc:"20 de daño a TODOS los enemigos. Aturde sus habilidades físicas 1 turno. Aturde sus habilidades de instinto 1 turno.",
      costo:["sabana", "comodin"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "todos"}, {"t": "aturdir", "turnos": 1, "obj": "todos", "clase": "fisico"}, {"t": "aturdir", "turnos": 1, "obj": "todos", "clase": "instinto"}] },
    { n:"Postura defensiva", desc:"Gana 30 de defensa destructible.",
      costo:["sabana", "comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "defensa", "v": 30, "obj": "self"}] },
    { n:"Salto evasivo", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Kabuto Yakushi · Shippuden
  serpiente: { habs: [
    { n:"Colmillos de terciopelo", desc:"20 de daño a un enemigo (ignora la defensa).",
      costo:["agua"], recarga:0, clases:["natural", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Muda de piel", desc:"Cura 15 a sí mismo. Cura 5 por turno durante 5 turnos a sí mismo. Le quita los efectos dañinos.",
      costo:["agua"], recarga:5, clases:["natural"],
      efectos:[{"t": "curar", "v": 15, "obj": "self"}, {"t": "curarTurnos", "v": 5, "turnos": 5, "obj": "self"}, {"t": "limpiar", "obj": "self"}] },
    { n:"Mordida neurotóxica", desc:"Lo aturde 1 turno.",
      costo:["sabana"], recarga:2, clases:["instinto", "rango"],
      efectos:[{"t": "aturdir", "turnos": 1, "obj": "todos"}] },
    { n:"Mimetismo en hojarasca", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Zaku Abumi · Original (Parte 1)
  sapo_marino: { habs: [
    { n:"Lengua pegajosa", desc:"25 de daño a un enemigo.",
      costo:["montana"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 25, "obj": "enemigo"}] },
    { n:"Contraataque reflejo", desc:"Contraataca: quien lo golpee recibe 25.",
      costo:["comodin"], recarga:2, clases:["fisico"],
      efectos:[{"t": "contraataque", "v": 25, "obj": "self"}] },
    { n:"Proyectil certero", desc:"45 de daño a TODOS los enemigos.",
      costo:["montana", "comodin", "comodin"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 45, "obj": "todos"}] },
    { n:"Inflado defensivo", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Konohamaru Sarutobi · Shippuden
  mono_titi: { habs: [
    { n:"Acicalado social", desc:"Recibe 10 menos de daño durante 3 turnos.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "reducir", "v": 10, "turnos": 3, "obj": "self"}] },
    { n:"Golpe", desc:"10 de daño a un enemigo. Su próximo golpe pega +5.",
      costo:["comodin"], recarga:3, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}, {"t": "amplificar", "v": 5, "turnos": 2, "obj": "self"}] },
    { n:"Lanzamiento de ramas", desc:"10 de daño a un enemigo.",
      costo:["bosque"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}] },
    { n:"Salto entre ramas", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Tsume Inuzuka · Original (Parte 1)
  zorro_gris: { habs: [
    { n:"Mordida", desc:"10 de daño a un enemigo. Recibe 10 menos de daño durante 4 turnos.",
      costo:["comodin"], recarga:4, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}, {"t": "reducir", "v": 10, "turnos": 4, "obj": "self"}] },
    { n:"Mordida y sacudida", desc:"15 de daño a un enemigo (ignora la defensa). Su próximo golpe pega +5.",
      costo:["comodin"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "ignoraDefensa": true}, {"t": "amplificar", "v": 5, "turnos": 2, "obj": "self"}] },
    { n:"Postura defensiva", desc:"Invulnerable 1 turno a todo el equipo.",
      costo:["comodin"], recarga:1, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "equipo"}] },
    { n:"Huida astuta", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Kushina Uzumaki · Original (Parte 1)
  boa: { habs: [
    { n:"Golpe aturdidor", desc:"15 de daño a un enemigo (ignora la defensa). Lo aturde 1 turno.",
      costo:["sabana", "comodin"], recarga:1, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "ignoraDefensa": true}, {"t": "aturdir", "turnos": 1, "obj": "enemigo"}] },
    { n:"Silbido", desc:"Lo marca: recibe +15 de daño de ahí en adelante.",
      costo:["sabana", "comodin"], recarga:5, clases:["instinto", "rango"],
      efectos:[{"t": "marcaPermanente", "v": 15, "obj": "enemigo"}] },
    { n:"Sacudida paralizante", desc:"Lo aturde 2 turnos.",
      costo:["montana", "sabana"], recarga:4, clases:["natural", "rango"],
      efectos:[{"t": "aturdir", "turnos": 2, "obj": "enemigo"}] },
    { n:"Evasión ágil", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Hashirama Senju · Revividos (Edo Tensei)
  danta: { habs: [
    { n:"Cuero grueso", desc:"Invulnerable 1 turno.",
      costo:["montana", "comodin"], recarga:2, clases:["natural", "melee"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
    { n:"Embestida", desc:"20 de daño a un enemigo.",
      costo:["montana", "comodin"], recarga:2, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}] },
    { n:"Postura defensiva", desc:"Gana 30 de defensa destructible permanente a todo el equipo.",
      costo:["montana", "montana"], recarga:5, clases:["fisico"],
      efectos:[{"t": "defensa", "v": 30, "obj": "equipo", "permanente": true}] },
    { n:"Huida veloz", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Young Kakashi · Original (Parte 1)
  coyote: { habs: [
    { n:"Estocada perforante", desc:"20 de daño a un enemigo (ignora la defensa).",
      costo:["bosque"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Toxina corrosiva", desc:"20 de daño a un enemigo (ignora la defensa).",
      costo:["agua"], recarga:0, clases:["toxina", "natural", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Golpe aturdidor", desc:"Gana 1 de energía.",
      costo:[], recarga:1, clases:["instinto", "rango"],
      efectos:[{"t": "darEnergia", "tipo": "comodin", "obj": "self"}] },
    { n:"Evasión ágil", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Rin Nohara · Original (Parte 1)
  colibri_fuego: { habs: [
    { n:"Pico como aguja", desc:"30 de daño a un enemigo (ignora la defensa, ignora la invulnerabilidad). Recibe 15 menos de daño durante 1 turnos.",
      costo:["sabana"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 30, "obj": "enemigo", "ignoraDefensa": true, "ignoraInvulnerable": true}, {"t": "reducir", "v": 15, "turnos": 1, "obj": "self"}] },
    { n:"Recuperación", desc:"Cura 25 a un aliado.",
      costo:["agua"], recarga:0, clases:["natural"],
      efectos:[{"t": "curar", "v": 25, "obj": "aliado"}] },
    { n:"Regeneración", desc:"Cura 10 por turno durante 3 turnos a un aliado.",
      costo:["comodin", "comodin"], recarga:3, clases:["fisico"],
      efectos:[{"t": "curarTurnos", "v": 10, "turnos": 3, "obj": "aliado"}] },
    { n:"Vuelo suspendido", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Obito Uchiha · Original (Parte 1)
  basilisco: { habs: [
    { n:"Mordida", desc:"15 de daño a un enemigo (ignora la defensa). Su próximo golpe pega +10.",
      costo:["comodin"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "ignoraDefensa": true}, {"t": "amplificar", "v": 10, "turnos": 2, "obj": "self"}] },
    { n:"Toxina corrosiva", desc:"15 de daño a un enemigo (toxina: atraviesa la invulnerabilidad). 15 de toxina por turno durante 2 turnos a un enemigo.",
      costo:["agua"], recarga:1, clases:["toxina", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "toxina": true}, {"t": "danoTurnos", "v": 15, "turnos": 2, "obj": "enemigo"}] },
    { n:"Ponzoña persistente", desc:"Recibe 15 menos de daño durante 4 turnos a un aliado.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "reducir", "v": 15, "turnos": 4, "obj": "aliado"}] },
    { n:"Carrera sobre el agua", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Sakura Haruno · Shippuden
  escarabajo: { habs: [
    { n:"Embestida aturdidora", desc:"20 de daño a un enemigo. Aturde sus habilidades físicas 1 turno. Aturde sus habilidades de instinto 1 turno. Su próximo golpe pega +10.",
      costo:["bosque"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "fisico"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "instinto"}, {"t": "amplificar", "v": 10, "turnos": 2, "obj": "self"}] },
    { n:"Recuperación", desc:"Cura 25 a un aliado.",
      costo:["agua"], recarga:0, clases:["natural"],
      efectos:[{"t": "curar", "v": 25, "obj": "aliado"}] },
    { n:"Embestida de cuerno", desc:"Recibe 10 menos de daño durante 4 turnos.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "reducir", "v": 10, "turnos": 4, "obj": "self"}] },
    { n:"Excavación", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Hinata Hyūga · Shippuden
  colibri_talamanca: { habs: [
    { n:"Picotazo", desc:"20 de daño a un enemigo.",
      costo:["bosque", "comodin"], recarga:1, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}] },
    { n:"Embestida feroz", desc:"15 de daño a TODOS los enemigos. Gana 10 de defensa destructible. Su próximo golpe pega +5.",
      costo:["agua", "comodin"], recarga:0, clases:["natural", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "todos"}, {"t": "defensa", "v": 10, "obj": "self"}, {"t": "amplificar", "v": 5, "turnos": 2, "obj": "self"}] },
    { n:"Golpe demoledor", desc:"Recibe 15 menos de daño durante 4 turnos.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "reducir", "v": 15, "turnos": 4, "obj": "self"}] },
    { n:"Vuelo veloz", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Kitsuchi · Shippuden
  armadillo: { habs: [
    { n:"Coraza reactiva", desc:"35 de daño a un enemigo.",
      costo:["bosque", "comodin"], recarga:1, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 35, "obj": "enemigo"}] },
    { n:"Contraataque reflejo", desc:"10 de daño a un enemigo.",
      costo:["montana"], recarga:2, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}] },
    { n:"Golpe aturdidor", desc:"45 de daño a un enemigo. Aturde sus habilidades físicas 2 turnos. Aturde sus habilidades de instinto 2 turnos.",
      costo:["montana", "montana"], recarga:2, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 45, "obj": "enemigo"}, {"t": "aturdir", "turnos": 2, "obj": "enemigo", "clase": "fisico"}, {"t": "aturdir", "turnos": 2, "obj": "enemigo", "clase": "instinto"}] },
    { n:"Madriguera", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Tenten · Shippuden
  puercoespin: { habs: [
    { n:"Proyectil certero", desc:"20 de daño a TODOS los enemigos (ignora la invulnerabilidad).",
      costo:["bosque"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "todos", "ignoraInvulnerable": true}] },
    { n:"Descarga a distancia", desc:"5 de daño a TODOS los enemigos (ignora la invulnerabilidad).",
      costo:["comodin"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 5, "obj": "todos", "ignoraInvulnerable": true}] },
    { n:"Púas defensivas", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:1, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
    { n:"Huida veloz", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Jiraiya · Shippuden
  sapo_dorado: { habs: [
    { n:"Bufotoxina", desc:"20 de daño a un enemigo.",
      costo:["agua"], recarga:0, clases:["toxina", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}] },
    { n:"Secreción de las parótidas", desc:"Queda expuesto 2 turnos (no puede volverse invulnerable).",
      costo:["sabana"], recarga:3, clases:["rango"],
      efectos:[{"t": "exponer", "turnos": 2, "obj": "todos"}] },
    { n:"Toxina corrosiva", desc:"25 de daño a TODOS los enemigos (toxina: atraviesa la invulnerabilidad, ignora la invulnerabilidad).",
      costo:["bosque", "montana", "sabana"], recarga:0, clases:["toxina", "rango"],
      efectos:[{"t": "dano", "v": 25, "obj": "todos", "toxina": true, "ignoraInvulnerable": true}] },
    { n:"Ocultamiento", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Hiruzen Sarutobi · Original (Parte 1)
  mono_congo: { habs: [
    { n:"Toxina corrosiva", desc:"20 de daño a un enemigo (toxina: atraviesa la invulnerabilidad). 10 de toxina por turno durante 2 turnos a un enemigo.",
      costo:["agua", "comodin"], recarga:0, clases:["toxina", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo", "toxina": true}, {"t": "danoTurnos", "v": 10, "turnos": 2, "obj": "enemigo"}] },
    { n:"Ponzoña persistente", desc:"40 de daño a un enemigo (toxina: atraviesa la invulnerabilidad, ignora la invulnerabilidad).",
      costo:["agua", "comodin"], recarga:0, clases:["rango"],
      efectos:[{"t": "dano", "v": 40, "obj": "enemigo", "toxina": true, "ignoraInvulnerable": true}] },
    { n:"Mordida", desc:"5 de daño a TODOS los enemigos (ignora la invulnerabilidad). Recibe 5 menos de daño durante 1 turnos.",
      costo:["bosque", "agua", "sabana"], recarga:0, clases:["melee"],
      efectos:[{"t": "dano", "v": 5, "obj": "todos", "ignoraInvulnerable": true}, {"t": "reducir", "v": 5, "turnos": 1, "obj": "self"}] },
    { n:"Braquiación evasiva", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Yūgao Uzuki · Original (Parte 1)
  manigordo: { habs: [
    { n:"Zarpazo desgarrador", desc:"50 de daño a un enemigo.",
      costo:["bosque", "sabana"], recarga:1, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 50, "obj": "enemigo"}] },
    { n:"Mordida al cráneo", desc:"Gana 20 de defensa destructible.",
      costo:["bosque"], recarga:0, clases:["fisico"],
      efectos:[{"t": "defensa", "v": 20, "obj": "self"}] },
    { n:"Contraataque reflejo", desc:"Queda expuesto 2 turnos (no puede volverse invulnerable).",
      costo:["sabana"], recarga:1, clases:[],
      efectos:[{"t": "exponer", "turnos": 2, "obj": "enemigo"}] },
    { n:"Acecho sigiloso", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Demon Brothers · Original (Parte 1)
  cangrejo: { habs: [
    { n:"Pinza inmovilizante", desc:"Aturde sus habilidades físicas 1 turno. Aturde sus habilidades naturales 1 turno.",
      costo:["bosque"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "fisico"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "natural"}] },
    { n:"Toxina corrosiva", desc:"30 de daño a un enemigo. Su próximo golpe pega +10.",
      costo:["comodin", "comodin"], recarga:0, clases:["fisico", "melee", "toxina"],
      efectos:[{"t": "dano", "v": 30, "obj": "enemigo"}, {"t": "amplificar", "v": 10, "turnos": 2, "obj": "self"}] },
    { n:"Caparazón", desc:"Gana 20 de defensa destructible permanente.",
      costo:["comodin", "comodin"], recarga:1, clases:["natural"],
      efectos:[{"t": "defensa", "v": 20, "obj": "self", "permanente": true}] },
    { n:"Enterramiento", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Iruka Umino · Original (Parte 1)
  delfin: { habs: [
    { n:"Ecolocalización de impacto", desc:"20 de daño a un enemigo.",
      costo:["bosque"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}] },
    { n:"Coordinación de manada", desc:"Invulnerable 1 turno a un aliado.",
      costo:["comodin"], recarga:1, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "aliado"}] },
    { n:"Proyectil certero", desc:"40 de daño a un enemigo (ignora la invulnerabilidad).",
      costo:["agua"], recarga:2, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 40, "obj": "enemigo", "ignoraInvulnerable": true}] },
    { n:"Inmersión profunda", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Mizuki · Original (Parte 1)
  puma: { habs: [
    { n:"Proyectil certero", desc:"15 de daño a un enemigo.",
      costo:["comodin"], recarga:1, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo"}] },
    { n:"Descarga a distancia", desc:"10 de daño a un enemigo.",
      costo:["bosque", "comodin"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}] },
    { n:"Acecho del puma", desc:"Invulnerable 1 turno.",
      costo:["sabana"], recarga:1, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
    { n:"Camuflaje en la maleza", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Anko Mitarashi · Original (Parte 1)
  bocaraca: { habs: [
    { n:"Embestida serpentina", desc:"5 de daño a un enemigo. Su próximo golpe pega +5.",
      costo:[], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 5, "obj": "enemigo"}, {"t": "amplificar", "v": 5, "turnos": 2, "obj": "self"}] },
    { n:"Ponzoña necrótica", desc:"10 de daño a TODOS los enemigos (toxina: atraviesa la invulnerabilidad).",
      costo:["agua"], recarga:2, clases:["toxina", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "todos", "toxina": true}] },
    { n:"Veneno neurotóxico", desc:"20 de daño a un enemigo. 5 de toxina por turno durante 3 turnos a un enemigo.",
      costo:["agua", "comodin"], recarga:0, clases:["toxina", "fisico", "melee"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}, {"t": "danoTurnos", "v": 5, "turnos": 3, "obj": "enemigo"}] },
    { n:"Evasión ágil", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Shizune · Original (Parte 1)
  coral: { habs: [
    { n:"Neurotoxina de coral", desc:"15 de daño a un enemigo.",
      costo:["comodin"], recarga:0, clases:["toxina", "fisico", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo"}] },
    { n:"Toxina corrosiva", desc:"10 de daño a un enemigo (toxina: atraviesa la invulnerabilidad). 10 de toxina por turno durante 3 turnos a un enemigo.",
      costo:["comodin"], recarga:1, clases:["toxina", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo", "toxina": true}, {"t": "danoTurnos", "v": 10, "turnos": 3, "obj": "enemigo"}] },
    { n:"Recuperación", desc:"Cura 35 a un aliado.",
      costo:["comodin", "comodin"], recarga:1, clases:["natural"],
      efectos:[{"t": "curar", "v": 35, "obj": "aliado"}] },
    { n:"Huida veloz", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Kurenai Yuhi · Original (Parte 1)
  mariposa_buho: { habs: [
    { n:"Proyectil certero", desc:"10 de daño a un enemigo. Gana 5 de defensa destructible.",
      costo:["sabana"], recarga:2, clases:["instinto", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}, {"t": "defensa", "v": 5, "obj": "self"}] },
    { n:"Postura defensiva", desc:"Gana 10 de defensa destructible permanente.",
      costo:["comodin"], recarga:2, clases:["instinto"],
      efectos:[{"t": "defensa", "v": 10, "obj": "self", "permanente": true}] },
    { n:"Golpe aturdidor", desc:"Lo aturde 2 turnos. Gana 5 de defensa destructible.",
      costo:["sabana", "sabana"], recarga:4, clases:["instinto", "rango"],
      efectos:[{"t": "aturdir", "turnos": 2, "obj": "enemigo"}, {"t": "defensa", "v": 5, "obj": "self"}] },
    { n:"Vuelo errático", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Asuma Sarutobi · Shippuden
  mono_arana: { habs: [
    { n:"Zarpazo", desc:"15 de daño a TODOS los enemigos (ignora la invulnerabilidad). Recibe 15 menos de daño durante 2 turnos.",
      costo:["bosque", "agua"], recarga:2, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "todos", "ignoraInvulnerable": true}, {"t": "reducir", "v": 15, "turnos": 2, "obj": "self"}] },
    { n:"Coordinación de tropa", desc:"Su próximo golpe pega +10.",
      costo:["comodin"], recarga:0, clases:["fisico"],
      efectos:[{"t": "amplificar", "v": 10, "turnos": 2, "obj": "self"}] },
    { n:"Contraataque reflejo", desc:"Contraataca: quien lo golpee recibe 25.",
      costo:["comodin"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "contraataque", "v": 25, "obj": "self"}] },
    { n:"Evasión ágil", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Curse Mark Sasuke · Original (Parte 1)
  cascabel: { habs: [
    { n:"Ponzoña persistente", desc:"45 de daño a un enemigo (ignora la defensa).",
      costo:["agua", "agua"], recarga:1, clases:["toxina", "natural", "melee"],
      efectos:[{"t": "dano", "v": 45, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Secreción tóxica", desc:"55 de daño a un enemigo. Lo aturde 2 turnos.",
      costo:["agua", "agua", "comodin"], recarga:5, clases:["toxina", "natural", "rango"],
      efectos:[{"t": "dano", "v": 55, "obj": "enemigo"}, {"t": "aturdir", "turnos": 2, "obj": "enemigo"}] },
    { n:"Regeneración", desc:"Invulnerable 1 turno.",
      costo:["montana"], recarga:1, clases:[],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
    { n:"Esquive instintivo", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Ao · Shippuden
  lechuza: { habs: [
    { n:"Carga veloz", desc:"10 de daño a un enemigo. Recibe 5 menos de daño durante 3 turnos.",
      costo:["sabana"], recarga:3, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}, {"t": "reducir", "v": 5, "turnos": 3, "obj": "self"}] },
    { n:"Rociada", desc:"25 de daño a un enemigo. Queda expuesto 1 turno (no puede volverse invulnerable).",
      costo:["montana"], recarga:0, clases:["instinto", "rango"],
      efectos:[{"t": "dano", "v": 25, "obj": "enemigo"}, {"t": "exponer", "turnos": 1, "obj": "enemigo"}] },
    { n:"Represalia", desc:"Contraataca: quien lo golpee recibe 25.",
      costo:["montana"], recarga:2, clases:["natural"],
      efectos:[{"t": "contraataque", "v": 25, "obj": "self"}] },
    { n:"Esquive instintivo", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Madara Uchiha · Shippuden
  jaguar: { habs: [
    { n:"Toxina corrosiva", desc:"Recibe 10 menos de daño durante 4 turnos.",
      costo:["comodin"], recarga:0, clases:["instinto"],
      efectos:[{"t": "reducir", "v": 10, "turnos": 4, "obj": "self"}] },
    { n:"Postura de acecho", desc:"Gana 70 de defensa destructible permanente.",
      costo:["montana", "montana"], recarga:6, clases:["natural"],
      efectos:[{"t": "defensa", "v": 70, "obj": "self", "permanente": true}] },
    { n:"Ponzoña persistente", desc:"10 de daño a un enemigo.",
      costo:["agua"], recarga:1, clases:["toxina"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}] },
    { n:"Evasión ágil", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Deva Path Pain · Shippuden
  aguila_harpia: { habs: [
    { n:"Púas defensivas", desc:"20 de daño a un enemigo (ignora la invulnerabilidad). Contraataca: quien lo golpee recibe 25.",
      costo:["sabana"], recarga:0, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo", "ignoraInvulnerable": true}, {"t": "contraataque", "v": 25, "obj": "self"}] },
    { n:"Golpe aturdidor", desc:"15 de daño a un enemigo (ignora la defensa).",
      costo:["bosque"], recarga:1, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Caída en picada", desc:"45 de daño a un enemigo (ignora la defensa).",
      costo:["bosque", "montana", "sabana"], recarga:3, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 45, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Repliegue", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Konan · Shippuden
  mariposa: { habs: [
    { n:"Estocada perforante", desc:"25 de daño a un enemigo (ignora la defensa). Su próximo golpe pega +5.",
      costo:["montana"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 25, "obj": "enemigo", "ignoraDefensa": true}, {"t": "amplificar", "v": 5, "turnos": 2, "obj": "self"}] },
    { n:"Sacudida paralizante", desc:"15 de daño a un enemigo.",
      costo:["montana", "agua"], recarga:3, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo"}] },
    { n:"Descarga a distancia", desc:"25 de daño a un enemigo.",
      costo:["agua", "comodin"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 25, "obj": "enemigo"}] },
    { n:"Mimetismo alar", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Yugito Nii · Shippuden
  leon_brenero: { habs: [
    { n:"Emboscada felina", desc:"Entra en modo especial 4 turnos. Recibe 15 menos de daño durante 4 turnos.",
      costo:[], recarga:0, clases:["natural"],
      efectos:[{"t": "modo", "turnos": 4, "obj": "self"}, {"t": "reducir", "v": 15, "turnos": 4, "obj": "self"}] },
    { n:"Secreción tóxica", desc:"30 de daño a un enemigo.",
      costo:["montana", "comodin"], recarga:1, clases:["toxina", "natural", "rango"],
      efectos:[{"t": "dano", "v": 30, "obj": "enemigo"}] },
    { n:"Garra letal", desc:"15 de daño a un enemigo.",
      costo:["montana"], recarga:1, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo"}] },
    { n:"Huida veloz", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Mei Terumi · Shippuden
  rana_verdinegra: { habs: [
    { n:"Batracotoxina", desc:"15 de daño a un enemigo (toxina: atraviesa la invulnerabilidad).",
      costo:["montana"], recarga:3, clases:["toxina", "natural", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "toxina": true}] },
    { n:"Estocada perforante", desc:"20 de daño a TODOS los enemigos (ignora la defensa).",
      costo:["agua", "comodin"], recarga:1, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "todos", "ignoraDefensa": true}] },
    { n:"Alcaloides cutáneos", desc:"10 de daño a TODOS los enemigos (toxina: atraviesa la invulnerabilidad).",
      costo:["montana", "comodin"], recarga:3, clases:["toxina", "natural", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "todos", "toxina": true}] },
    { n:"Coloración aposemática", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Jūgo · Shippuden
  chancho_monte: { habs: [
    { n:"Embestida aturdidora", desc:"40 de daño a un enemigo. Aturde sus habilidades físicas 1 turno. Aturde sus habilidades de cuerpo a cuerpo 1 turno.",
      costo:["bosque", "montana"], recarga:0, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 40, "obj": "enemigo"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "fisico"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "melee"}] },
    { n:"Cornada", desc:"25 de daño a un enemigo (ignora la defensa).",
      costo:["montana", "montana"], recarga:4, clases:["fisico", "melee"],
      efectos:[{"t": "dano", "v": 25, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Recuperación", desc:"Gana 20 de defensa destructible permanente a un aliado.",
      costo:["montana", "comodin"], recarga:1, clases:["natural"],
      efectos:[{"t": "defensa", "v": 20, "obj": "aliado", "permanente": true}] },
    { n:"Estampida", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Toroi · Revividos (Edo Tensei)
  mantarraya: { habs: [
    { n:"Rociada", desc:"20 de daño a un enemigo.",
      costo:["comodin"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo"}] },
    { n:"Coletazo", desc:"Recibe 15 menos de daño durante 3 turnos.",
      costo:[], recarga:2, clases:["fisico"],
      efectos:[{"t": "reducir", "v": 15, "turnos": 3, "obj": "self"}] },
    { n:"Aguijón caudal", desc:"10 de daño a TODOS los enemigos (ignora la defensa).",
      costo:["montana"], recarga:1, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "todos", "ignoraDefensa": true}] },
    { n:"Esquive instintivo", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Tobirama Senju · Revividos (Edo Tensei)
  cocodrilo: { habs: [
    { n:"Proyectil certero", desc:"15 de daño a un enemigo.",
      costo:["agua"], recarga:0, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo"}] },
    { n:"Mordida y giro", desc:"15 de daño a un enemigo.",
      costo:["agua", "sabana"], recarga:3, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo"}] },
    { n:"Piel acorazada", desc:"Invulnerable 1 turno.",
      costo:["sabana"], recarga:3, clases:["instinto"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
    { n:"Emboscada sumergida", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Mū · Revividos (Edo Tensei)
  geco: { habs: [
    { n:"Empalada", desc:"25 de daño a un enemigo (ignora la defensa, ignora la invulnerabilidad).",
      costo:["agua", "comodin"], recarga:0, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 25, "obj": "enemigo", "ignoraDefensa": true, "ignoraInvulnerable": true}] },
    { n:"Sacudida paralizante", desc:"Recibe 15 menos de daño durante 2 turnos. Cura 15 a sí mismo.",
      costo:["agua"], recarga:4, clases:["natural"],
      efectos:[{"t": "reducir", "v": 15, "turnos": 2, "obj": "self"}, {"t": "curar", "v": 15, "obj": "self"}] },
    { n:"Perforación", desc:"40 de daño a un enemigo (ignora la defensa, ignora la invulnerabilidad).",
      costo:["agua", "comodin", "comodin"], recarga:1, clases:["natural", "rango"],
      efectos:[{"t": "dano", "v": 40, "obj": "enemigo", "ignoraDefensa": true, "ignoraInvulnerable": true}] },
    { n:"Autotomía de cola", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["natural"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Hanzō · Revividos (Edo Tensei)
  salamandra: { habs: [
    { n:"Secreción cutánea tóxica", desc:"Gana 30 de defensa destructible.",
      costo:["comodin", "comodin", "comodin"], recarga:6, clases:[],
      efectos:[{"t": "defensa", "v": 30, "obj": "self"}] },
    { n:"Secreción cutánea", desc:"15 de daño a un enemigo (ignora la defensa). 5 de toxina por turno durante 2 turnos a un enemigo.",
      costo:["bosque"], recarga:1, clases:["toxina", "fisico", "melee"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "ignoraDefensa": true}, {"t": "danoTurnos", "v": 5, "turnos": 2, "obj": "enemigo"}] },
    { n:"Toxina corrosiva", desc:"20 de daño a un enemigo (toxina: atraviesa la invulnerabilidad).",
      costo:["montana"], recarga:0, clases:["fisico", "toxina"],
      efectos:[{"t": "dano", "v": 20, "obj": "enemigo", "toxina": true}] },
    { n:"Ocultamiento", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
  // Fuguki Suikazan · Revividos (Edo Tensei)
  tiburon_martillo: { habs: [
    { n:"Punzada profunda", desc:"15 de daño a un enemigo (ignora la defensa).",
      costo:["agua"], recarga:1, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 15, "obj": "enemigo", "ignoraDefensa": true}] },
    { n:"Dentellada frenética", desc:"Recibe 5 menos de daño durante 2 turnos.",
      costo:["agua"], recarga:5, clases:["natural"],
      efectos:[{"t": "reducir", "v": 5, "turnos": 2, "obj": "self"}] },
    { n:"Sacudida paralizante", desc:"10 de daño a un enemigo. Aturde sus habilidades físicas 1 turno. Aturde sus habilidades naturales 1 turno.",
      costo:["agua", "comodin"], recarga:2, clases:["fisico", "rango"],
      efectos:[{"t": "dano", "v": 10, "obj": "enemigo"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "fisico"}, {"t": "aturdir", "turnos": 1, "obj": "enemigo", "clase": "natural"}] },
    { n:"Esquive instintivo", desc:"Invulnerable 1 turno.",
      costo:["comodin"], recarga:4, clases:["fisico"],
      efectos:[{"t": "invulnerable", "turnos": 1, "obj": "self"}] },
  ] },
};

// Kits alternativos que trae el documento para el mismo animal (otras
// versiones del personaje original). Todavía no se usan.
export const VARIANTES_DOC = {"serpiente": ["Kabuto Yakushi", "Reanimator Kabuto", "Sage Mode Kabuto"], "sapo_marino": ["Kurotsuchi"], "mono_titi": ["Konohamaru Sarutobi"], "zorro_gris": ["Naruto Uzumaki", "One-Tailed Naruto", "Nine-Tailed Naruto"], "boa": ["Naraka Path Pain", "Yamato"], "danta": ["Hashirama Senju"], "coyote": ["Kiba Inuzuka", "Kakashi Hatake"], "basilisco": ["Masked Man", "Tobi"], "escarabajo": ["Sakura Haruno", "Kinkaku", "Fukai"], "colibri_talamanca": ["Hinata Hyūga"], "armadillo": ["Chōji Akimichi"], "puercoespin": ["Kimimaro", "Tenten"], "sapo_dorado": ["Jiraiya", "Sage Mode Naruto", "Sage Mode Jiraiya"], "puma": ["A"], "mono_arana": ["Asuma Sarutobi"], "lechuza": ["Chūkichi"], "mariposa": ["Konan of the Rain"], "chancho_monte": ["Curse Mark Jūgo"]};
